pair_name: gpt2

teacher:
  model_name: gpt2-xl
  batch_size: 32

student:
  model_name: gpt2

mta:
  word_layers: [6]
  phrase_layers: [9, 12]
  lambda_dsa: 2.0
  lambda_hid: 0.2

train:
  lr: 1e-4
  projector_lr: 5e-4
  epochs: 5
  batch_size: 48
  scheduler: cosine
  save_steps: 200

eval:
  batch_size: 32

distillm2:
  gen_batch_size: 64
